//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub did: u64,
  pub user_agent: Option<String>,
  pub login_by_uid: Option<u64>,
  pub last_login_datetime: DateTime,
  pub last_login_ip: String,
  #[sea_orm(
    belongs_to,
    from = "login_by_uid",
    to = "uid",
    on_update = "Restrict",
    on_delete = "Restrict"
  )]
  pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
