//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "librarys")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub lid: u64,
  pub name: Option<String>,
  pub description: Option<String>,
  pub create_datetime: DateTime,
  pub last_update_datetime: DateTime,
  pub r#type: Option<u64>,
  pub create_by_uid: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::library_paths::Entity")]
  LibraryPaths,
  #[sea_orm(has_many = "super::librarys_related_tags::Entity")]
  LibrarysRelatedTags,
  #[sea_orm(has_many = "super::resources::Entity")]
  Resources,
  #[sea_orm(
    belongs_to = "super::types::Entity",
    from = "Column::Type",
    to = "super::types::Column::Tid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Types,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::CreateByUid",
    to = "super::users::Column::Uid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::library_paths::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::LibraryPaths.def()
  }
}

impl Related<super::librarys_related_tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::LibrarysRelatedTags.def()
  }
}

impl Related<super::resources::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Resources.def()
  }
}

impl Related<super::types::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Types.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
