//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "librarys_related_tags")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub lrtid: u64,
  pub lid: u64,
  pub tid: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::librarys::Entity",
    from = "Column::Lid",
    to = "super::librarys::Column::Lid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Librarys,
  #[sea_orm(
    belongs_to = "super::tags::Entity",
    from = "Column::Tid",
    to = "super::tags::Column::Tid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Tags,
}

impl Related<super::librarys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Librarys.def()
  }
}

impl Related<super::tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tags.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
