//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "metadata_indexes")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub mid: u64,
  pub path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::resources::Entity")]
  Resources,
}

impl Related<super::resources::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Resources.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
