//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

pub mod prelude;

pub mod devices;
pub mod library_paths;
pub mod librarys;
pub mod librarys_related_tags;
pub mod path_mappings;
pub mod permissions;
pub mod resources;
pub mod resources_related_tags;
pub mod roles;
pub mod roles_related_permissions;
pub mod settings;
pub mod tag_groups;
pub mod tags;
pub mod types;
pub mod users;
pub mod users_related_roles;
