//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "path_mappings")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub pmid: u64,
  pub path: Option<String>,
  pub content_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
