//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "path_mappings")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub pmid: u64,
  pub path: String,
  pub mime_type: String,
  #[sea_orm(has_many)]
  pub resources: HasMany<super::resources::Entity>,
  #[sea_orm(has_many)]
  pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
