//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub pid: u64,
  #[sea_orm(unique)]
  pub name: String,
  pub description: Option<String>,
  pub builtin: i8,
  #[sea_orm(has_many)]
  pub roles_related_permissions: HasMany<super::roles_related_permissions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
