//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "resources")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub rid: u64,
  pub name: Option<String>,
  pub description: Option<String>,
  pub lid: Option<u64>,
  pub create_datetime: DateTime,
  pub last_update_datetime: DateTime,
  pub metadata_index: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::librarys::Entity",
    from = "Column::Lid",
    to = "super::librarys::Column::Lid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Librarys,
  #[sea_orm(
    belongs_to = "super::metadata_indexes::Entity",
    from = "Column::MetadataIndex",
    to = "super::metadata_indexes::Column::Mid",
    on_update = "Restrict",
    on_delete = "Restrict"
  )]
  MetadataIndexes,
  #[sea_orm(has_many = "super::resources_related_tags::Entity")]
  ResourcesRelatedTags,
}

impl Related<super::librarys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Librarys.def()
  }
}

impl Related<super::metadata_indexes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MetadataIndexes.def()
  }
}

impl Related<super::resources_related_tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ResourcesRelatedTags.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
