//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "resources")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub rid: u64,
  pub name: Option<String>,
  pub description: Option<String>,
  pub lid: Option<u64>,
  pub create_datetime: DateTime,
  pub last_update_datetime: DateTime,
  pub metadata_index: Option<u64>,
  #[sea_orm(
    belongs_to,
    from = "lid",
    to = "lid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub librarys: HasOne<super::librarys::Entity>,
  #[sea_orm(
    belongs_to,
    from = "metadata_index",
    to = "mid",
    on_update = "Restrict",
    on_delete = "Restrict"
  )]
  pub metadata_indexes: HasOne<super::metadata_indexes::Entity>,
  #[sea_orm(has_many)]
  pub resources_related_tags: HasMany<super::resources_related_tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
