//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub rid: u64,
  pub name: String,
  pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::roles_related_permissions::Entity")]
  RolesRelatedPermissions,
  #[sea_orm(has_many = "super::users_related_roles::Entity")]
  UsersRelatedRoles,
}

impl Related<super::roles_related_permissions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::RolesRelatedPermissions.def()
  }
}

impl Related<super::users_related_roles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UsersRelatedRoles.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
