//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "roles_related_permissions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub rrpid: u64,
  pub rid: u64,
  pub pid: u64,
  pub builtin: i8,
  #[sea_orm(
    belongs_to,
    from = "pid",
    to = "pid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub permissions: HasOne<super::permissions::Entity>,
  #[sea_orm(
    belongs_to,
    from = "rid",
    to = "rid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub roles: HasOne<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
