//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles_related_permissions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub rrpid: u64,
  pub rid: u64,
  pub pid: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::permissions::Entity",
    from = "Column::Pid",
    to = "super::permissions::Column::Pid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Permissions,
  #[sea_orm(
    belongs_to = "super::roles::Entity",
    from = "Column::Rid",
    to = "super::roles::Column::Rid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Roles,
}

impl Related<super::permissions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Permissions.def()
  }
}

impl Related<super::roles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Roles.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
