//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub tid: u64,
  #[sea_orm(unique_key = "tags_unique")]
  pub tgid: u64,
  #[sea_orm(unique, unique_key = "tags_unique")]
  pub text: String,
  pub create_datetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::librarys_related_tags::Entity")]
  LibrarysRelatedTags,
  #[sea_orm(has_many = "super::resources_related_tags::Entity")]
  ResourcesRelatedTags,
  #[sea_orm(
    belongs_to = "super::tag_groups::Entity",
    from = "Column::Tgid",
    to = "super::tag_groups::Column::Tgid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TagGroups,
}

impl Related<super::librarys_related_tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::LibrarysRelatedTags.def()
  }
}

impl Related<super::resources_related_tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ResourcesRelatedTags.def()
  }
}

impl Related<super::tag_groups::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TagGroups.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
