//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub tid: u64,
  #[sea_orm(unique_key = "tags_unique")]
  pub tgid: u64,
  #[sea_orm(unique, unique_key = "tags_unique")]
  pub text: String,
  pub create_datetime: DateTime,
  #[sea_orm(has_many)]
  pub librarys_related_tags: HasMany<super::librarys_related_tags::Entity>,
  #[sea_orm(has_many)]
  pub resources_related_tags: HasMany<super::resources_related_tags::Entity>,
  #[sea_orm(
    belongs_to,
    from = "tgid",
    to = "tgid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub tag_groups: HasOne<super::tag_groups::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
