//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "types")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub tid: u64,
  pub scan_mode: Option<String>,
  pub label: Option<String>,
  #[sea_orm(has_many)]
  pub librarys: HasMany<super::librarys::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
