//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "types")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub tid: u64,
  pub scan_mode: Option<String>,
  pub label: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::librarys::Entity")]
  Librarys,
}

impl Related<super::librarys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Librarys.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
