//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users_related_roles")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub urrid: u64,
  pub uid: u64,
  pub rid: u64,
  #[sea_orm(
    belongs_to,
    from = "rid",
    to = "rid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub roles: HasOne<super::roles::Entity>,
  #[sea_orm(
    belongs_to,
    from = "uid",
    to = "uid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
