//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub uid: u64,
  pub password: String,
  #[sea_orm(unique)]
  pub username: String,
  pub avatar: Option<u64>,
  pub nickname: Option<String>,
  pub create_datetime: DateTime,
  pub last_update_datetime: DateTime,
  pub email: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::devices::Entity")]
  Devices,
  #[sea_orm(has_many = "super::librarys::Entity")]
  Librarys,
  #[sea_orm(
    belongs_to = "super::path_mappings::Entity",
    from = "Column::Avatar",
    to = "super::path_mappings::Column::Pmid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  PathMappings,
  #[sea_orm(has_many = "super::users_related_roles::Entity")]
  UsersRelatedRoles,
}

impl Related<super::devices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Devices.def()
  }
}

impl Related<super::librarys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Librarys.def()
  }
}

impl Related<super::path_mappings::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::PathMappings.def()
  }
}

impl Related<super::users_related_roles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::UsersRelatedRoles.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
