//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub uid: u64,
  pub password: String,
  #[sea_orm(unique)]
  pub username: String,
  pub avatar: Option<u64>,
  pub nickname: Option<String>,
  pub create_datetime: DateTime,
  pub last_update_datetime: DateTime,
  pub email: Option<String>,
  #[sea_orm(has_many)]
  pub devices: HasMany<super::devices::Entity>,
  #[sea_orm(has_many)]
  pub librarys: HasMany<super::librarys::Entity>,
  #[sea_orm(
    belongs_to,
    from = "avatar",
    to = "pmid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub path_mappings: HasOne<super::path_mappings::Entity>,
  #[sea_orm(has_many)]
  pub users_related_roles: HasMany<super::users_related_roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
