//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users_related_roles")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub urrid: u64,
  pub uid: u64,
  pub rid: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::roles::Entity",
    from = "Column::Rid",
    to = "super::roles::Column::Rid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Roles,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::Uid",
    to = "super::users::Column::Uid",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::roles::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Roles.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
