//! Typed view wrappers over the raw wasmtime-generated context handles.
//!
//! The [`MetadataHandle`] / [`PathMappingHandle`] / [`TagHandle`] types
//! generated by `wit-bindgen` are low-level: every field read/write is a
//! `bincode` round-trip through `list<u8>`, every query needs a
//! [`MetadataQuery`], and extend keys must be spelled verbatim. These views
//! hide all of that:
//!
//! - [`MetadataView::query`] returns a decoded [`Metadata`] node directly.
//! - [`MetadataView::query_field`] decodes the value into `T` for you.
//! - [`MetadataView::insert`] accepts a [`Metadata`] node and encodes it.
//! - [`MetadataView::read_extend`] / [`MetadataView::write_extend`] exchange
//!   plugin-defined `MetadataExtend` structs directly, handling the
//!   `EXTEND_KEY:` prefix internally.
//!
//! The handle types are `!Clone` (wit-bindgen guest resources), so a view
//! borrows its handle: `'a` is the lifetime of the borrowed handle. Create a
//! view with [`ToView`] (`handle.to_view()`); get the borrowed raw handle
//! back with [`FromView`] (`MetadataHandle::from_view(view)`, consuming the
//! view).

use crate::extend::MetadataExtend;
use crate::metadata::{Metadata, MetadataType};

/// Raw wit-bindgen generated context types: the resource handles plus the
/// `MetadataQuery` variant and `PathMappingHandleError` they use.
pub use crate::api::bindings::cosmox::plugin::context::{
    MetadataHandle, MetadataQuery, PathMappingHandle, PathMappingHandleError, TagHandle,
};

/// Borrow back the raw context handle from a typed view, consuming it.
///
/// The inverse of [`ToView`]: `handle.to_view()` borrows `handle` into a
/// view, and `MetadataHandle::from_view(view)` consumes the view and returns
/// that borrow. The raw handle is always returned by reference because the
/// wit-bindgen handles are `!Clone`; the borrow outlives the consumed view
/// because it points at the original handle, not at `view` itself.
pub trait FromView: Sized {
    /// The typed view wrapping this raw handle.
    type View<'a>
    where
        Self: 'a;
    /// Consume `view`, returning the borrowed raw handle.
    fn from_view<'a>(view: Self::View<'a>) -> &'a Self
    where
        Self: 'a;
}

/// Convert a raw context handle into its typed view.
///
/// `handle.to_view()` is the single entry point the `#[on_event]` macro
/// generates when unpacking `EventContext` handles. Each raw handle type
/// implements this with its matching view type, so the macro never needs to
/// name a concrete view type.
pub trait ToView {
    /// The typed view produced by `to_view`.
    type View<'a>
    where
        Self: 'a;
    /// Convert `self` into the typed view.
    fn to_view(&self) -> Self::View<'_>;
}

/// A typed view over the raw [`MetadataHandle`].
///
/// Wraps every raw method with typed arguments/returns:
/// - `Vec<u8>` payloads become [`Metadata`] nodes or typed field values.
/// - `insert` / `modify` take decoded values and encode them internally.
/// - extend operations exchange `MetadataExtend` structs, hiding the
///   `EXTEND_KEY:` prefix convention.
#[derive(Clone)]
pub struct MetadataView<'a> {
    handle: &'a MetadataHandle,
}

impl FromView for MetadataHandle {
    type View<'a> = MetadataView<'a>;

    fn from_view<'a>(view: MetadataView<'a>) -> &'a MetadataHandle
    where
        Self: 'a,
    {
        view.handle
    }
}

impl ToView for MetadataHandle {
    type View<'a> = MetadataView<'a>;

    fn to_view(&self) -> MetadataView<'_> {
        MetadataView { handle: self }
    }
}

impl<'a> MetadataView<'a> {
    /// Read a whole node and decode it into a [`Metadata<T>`].
    ///
    /// `T` is a phantom marker: it does not participate in (de)serialization,
    /// so any `T` works (usually `()`, or a `MetadataExtend` struct for nodes
    /// carrying extension data). Returns `None` if the node does not exist or
    /// fails to decode.
    pub fn query<T>(&self, query: &MetadataQuery) -> Option<Metadata<T>> {
        let blob = self.handle.query(query)?;
        Metadata::bindecode(blob).ok().map(|node| (*node).clone())
    }

    /// Read a single field, decoding it into `T`.
    ///
    /// Returns `None` if the node/field does not exist. Decode failures
    /// propagate as `None` (the raw host call already bincode-encodes).
    pub fn query_field<T: bincode::Decode<()>>(
        &self,
        query: &MetadataQuery,
        field: &str,
    ) -> Option<T> {
        let blob = self.handle.query_field(query, field)?;
        bincode::decode_from_slice::<T, _>(&blob, bincode::config::standard())
            .ok()
            .map(|(value, _)| value)
    }

    /// Read the `metadata_type` field.
    pub fn metadata_type(&self, query: &MetadataQuery) -> Option<MetadataType> {
        self.query_field(query, "metadata_type")
    }

    /// Read the `name` field.
    pub fn name(&self, query: &MetadataQuery) -> Option<String> {
        self.query_field(query, "name")
    }

    /// Insert a node under `query`, encoding `data` internally.
    ///
    /// Returns the new node's rid.
    pub fn insert<T>(&self, query: &MetadataQuery, data: &Metadata<T>) -> Option<u64> {
        let blob = data.binencode().ok()?;
        Some(self.handle.insert(query, &blob))
    }

    /// Create a node with `name` and `metadata_type` under `query`.
    ///
    /// Convenience wrapper over [`Self::insert`]; returns the new rid.
    pub fn create_node(
        &self,
        parent: &MetadataQuery,
        name: &str,
        metadata_type: MetadataType,
    ) -> Option<u64> {
        let meta = Metadata::<()> {
            name: name.to_string(),
            metadata_type,
            ..Default::default()
        };
        self.insert(parent, &meta)
    }

    /// Modify a single field, encoding `value` internally.
    pub fn modify<T: bincode::Encode>(&self, query: &MetadataQuery, field: &str, value: &T) {
        if let Ok(blob) = bincode::encode_to_vec(value, bincode::config::standard()) {
            self.handle.modify(query, field, &blob);
        }
    }

    /// Delete a node.
    pub fn delete(&self, query: &MetadataQuery) {
        self.handle.delete(query);
    }

    /// List the rids of all children of `query`.
    pub fn children(&self, query: &MetadataQuery) -> Vec<u64> {
        self.handle.query_all(query)
    }

    /// Move `query` under `target`.
    pub fn move_node(&self, query: &MetadataQuery, target: &MetadataQuery) {
        self.handle.move_(query, target);
    }

    /// Move many nodes under `target` in one call.
    pub fn move_by_ids(&self, target: &MetadataQuery, ids: &[u64]) {
        self.handle.move_by_ids(target, ids);
    }

    /// Delete many nodes in one call.
    pub fn delete_by_ids(&self, ids: &[u64]) {
        self.handle.delete_by_ids(ids);
    }

    /// Read a plugin-defined `MetadataExtend` struct out of `query`'s
    /// `extend` map (only `EXTEND_KEY:`-prefixed keys are collected).
    pub fn read_extend<T: MetadataExtend>(&self, query: &MetadataQuery) -> Option<T> {
        let meta = self.query::<()>(query)?;
        T::from_extend_pairs(&meta.extend).ok()
    }

    /// Write a plugin-defined `MetadataExtend` struct into `query`'s
    /// `extend` map, expanding `EXTEND_KEY:field` keys internally.
    pub fn write_extend<T: MetadataExtend>(&self, query: &MetadataQuery, data: T) {
        let pairs: Vec<(String, String)> = data.to_extend_pairs();
        if !pairs.is_empty() {
            self.handle.write_extend(query, &pairs);
        }
    }
}

/// A typed view over the raw [`PathMappingHandle`].
#[derive(Clone)]
pub struct PathMappingView<'a> {
    handle: &'a PathMappingHandle,
}

impl FromView for PathMappingHandle {
    type View<'a> = PathMappingView<'a>;

    fn from_view<'a>(view: PathMappingView<'a>) -> &'a PathMappingHandle
    where
        Self: 'a,
    {
        view.handle
    }
}

impl ToView for PathMappingHandle {
    type View<'a> = PathMappingView<'a>;

    fn to_view(&self) -> PathMappingView<'_> {
        PathMappingView { handle: self }
    }
}

impl<'a> PathMappingView<'a> {
    /// Map `link` to `rid` under the given `field`
    /// (`cover_file_map_id` / `data_file_map_id`).
    pub fn push(&self, rid: u64, field: &str, link: &str) -> Result<(), PathMappingHandleError> {
        self.handle.push(rid, field, link)
    }
}

/// A typed view over the raw [`TagHandle`].
#[derive(Clone)]
pub struct TagView<'a> {
    handle: &'a TagHandle,
}

impl FromView for TagHandle {
    type View<'a> = TagView<'a>;

    fn from_view<'a>(view: TagView<'a>) -> &'a TagHandle
    where
        Self: 'a,
    {
        view.handle
    }
}

impl ToView for TagHandle {
    type View<'a> = TagView<'a>;

    fn to_view(&self) -> TagView<'_> {
        TagView { handle: self }
    }
}

impl<'a> TagView<'a> {
    /// Add a single `(key, value)` tag to `rid`.
    pub fn add_tag(&self, rid: u64, label: (&str, &str)) -> Result<(), String> {
        self.handle.add_tag(rid, label)
    }

    /// Add many tags to `rid`.
    pub fn add_tags(&self, rid: u64, labels: &[(String, String)]) -> Result<(), String> {
        self.handle.add_tags(rid, labels)
    }

    /// Delete the tag(s) with id `tid`.
    pub fn delete_tag(&self, tid: u64) -> Result<(), String> {
        self.handle.delete_tag(tid)
    }
}
