//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "libraries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub lid: u64,
    pub name: Option<String>,
    pub description: Option<String>,
    pub create_datetime: DateTime,
    pub last_update_datetime: DateTime,
    pub r#type: u64,
    pub create_by_uid: u64,
    #[sea_orm(has_many)]
    pub libraries_related_tags: HasMany<super::libraries_related_tags::Entity>,
    #[sea_orm(has_many)]
    pub library_paths: HasMany<super::library_paths::Entity>,
    #[sea_orm(has_many)]
    pub resources: HasMany<super::resources::Entity>,
    #[sea_orm(
        belongs_to,
        from = "type",
        to = "tid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub types: HasOne<super::types::Entity>,
    #[sea_orm(
        belongs_to,
        from = "create_by_uid",
        to = "uid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
