//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "library_paths")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub lpid: u64,
    pub lid: u64,
    pub path: String,
    #[sea_orm(
        belongs_to,
        from = "lid",
        to = "lid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub libraries: HasOne<super::libraries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
