//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "metadata_indexes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub mid: u64,
    pub path: String,
    #[sea_orm(has_many)]
    pub resources: HasMany<super::resources::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
