//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "resources_related_tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rrtid: u64,
    pub rid: u64,
    pub tid: u64,
    #[sea_orm(
        belongs_to,
        from = "rid",
        to = "rid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub resources: HasOne<super::resources::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tid",
        to = "tid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub tags: HasOne<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
