//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rid: u64,
    pub name: Option<String>,
    pub description: Option<String>,
    pub lid: Option<u64>,
    pub create_datetime: DateTime,
    pub last_update_datetime: DateTime,
    pub metadata_index: Option<u64>,
    pub cover: Option<u64>,
    #[sea_orm(
        belongs_to,
        from = "lid",
        to = "lid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub libraries: HasOne<super::libraries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "metadata_index",
        to = "mid",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub metadata_indexes: HasOne<super::metadata_indexes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "cover",
        to = "pmid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub path_mappings: HasOne<super::path_mappings::Entity>,
    #[sea_orm(has_many)]
    pub resources_related_tags: HasMany<super::resources_related_tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
