//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "tag_groups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tgid: u64,
    #[sea_orm(unique)]
    pub text: String,
    pub create_datetime: DateTime,
    #[sea_orm(has_many)]
    pub tags: HasMany<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
