//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tid: u64,
    pub scan_mode: Option<String>,
    #[sea_orm(unique)]
    pub label: String,
    #[sea_orm(has_many)]
    pub libraries: HasMany<super::libraries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
